<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>io.qml4j</groupId>
  <artifactId>m0-smoke</artifactId>
  <version>0.0.1-SNAPSHOT</version>

  <properties>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
    <dependency>
      <groupId>io.github.humbleui</groupId>
      <artifactId>skija-shared</artifactId>
      <version>0.143.16</version>
    </dependency>
    <dependency>
      <groupId>io.github.humbleui</groupId>
      <artifactId>skija-linux-arm64</artifactId>
      <version>0.143.16</version>
    </dependency>
  </dependencies>
</project>
