<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.qml4j</groupId>
        <artifactId>qml4j-parent</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>qml4j-render</artifactId>

    <dependencies>
        <dependency>
            <groupId>io.qml4j</groupId>
            <artifactId>qml4j-parser</artifactId>
        </dependency>
        <dependency>
            <groupId>io.qml4j</groupId>
            <artifactId>qml4j-engine</artifactId>
        </dependency>
        <dependency>
            <groupId>io.qml4j</groupId>
            <artifactId>qml4j-compiler</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.humbleui</groupId>
            <artifactId>skija-shared</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
        </dependency>
    </dependencies>
</project>
